import { useState, useEffect, useMemo } from 'react';
import { useParams, useLocation, useNavigate, Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Clock, Car, RefreshCw, Ticket, ShieldPlus, Download,
  Wallet, ChevronDown, Gem, Loader2, Compass, CloudRain, Sun, Cloud,
  UtensilsCrossed, Bus, Sparkles, Plus, X, Trash2,
  Phone, MapPinned, CalendarHeart, Luggage, TimerReset, ListChecks, Gauge,
  Flag, ArrowDown, Route, Footprints, Bike, Train, TrainFront, Ship,
  Building2, Star, ExternalLink, IndianRupee
} from 'lucide-react';

const CROWD_COLOR = { low: '#16A34A', moderate: '#22C55E', high: '#2563EB' };

function JourneyEndpoint({ icon: Icon, label, location, time, timeLabel }) {
  if (!location) return null;
  return <div className="rounded-2xl bg-[#0C3B5E] text-white p-4 flex items-center gap-3"><div className="w-9 h-9 rounded-full bg-white/10 flex items-center justify-center shrink-0"><Icon size={16} className="text-[#22C55E]" /></div><div><p className="text-[10px] font-mono uppercase tracking-wide text-white/50">{label}</p><p className="font-bold text-sm">{location}</p>{time && <p className="text-xs text-white/70 mt-0.5">{timeLabel}: {time}</p>}</div></div>;
}

function TravelSegment({ from, to, distanceKm, minutes, mode }) {
  if (distanceKm == null && minutes == null && !mode) return null;
  return <div className="flex items-stretch gap-3 py-2"><div className="w-9 flex flex-col items-center shrink-0"><span className="w-px flex-1 bg-[#0C3B5E]/15" /><ArrowDown size={13} className="text-[#0C3B5E]/35 my-1" /><span className="w-px flex-1 bg-[#0C3B5E]/15" /></div><div className="flex-1 rounded-xl bg-[#0C3B5E]/[0.03] border border-dashed border-[#0C3B5E]/20 px-3 py-2 my-1">{from && <p className="text-[11px] text-[#0C3B5E]/50 mb-1">{from} → {to}</p>}<div className="flex flex-wrap gap-x-3 gap-y-0.5 text-xs text-[#0C3B5E]/70">{distanceKm != null && <span>{distanceKm} km</span>}{minutes != null && <span>{minutes} min</span>}{mode && <span className="capitalize">{mode.replace('_',' ')}</span>}</div></div></div>;
}

const MODE_ICON = { walk: Footprints, bicycle: Bike, bike_taxi: Bike, auto: Car, cab: Car, metro: TrainFront, local_bus: Bus, train: Train, ferry: Ship };
function ModeIcon({ mode, size = 13 }) { const Icon = MODE_ICON[mode] || Car; return <Icon size={size} />; }

function TransportLegCard({ transport, from, to }) {
  const [expanded, setExpanded] = useState(false);
  if (!transport) return null;
  const detail = transport.recommended_mode === 'local_bus' ? `${transport.vehicle_name || 'Bus'} ${transport.vehicle_number || ''} · ${transport.boarding_point || ''} → ${transport.destination_point || ''}` : transport.recommended_mode === 'train' ? `${transport.vehicle_name || 'Train'} (${transport.vehicle_number || ''}) · ${transport.boarding_point || ''} → ${transport.destination_point || ''}` : transport.recommended_mode === 'metro' ? `${transport.details?.metro_line || 'Metro'} · ${transport.details?.boarding_station || ''} → ${transport.details?.destination_station || ''}` : transport.details?.recommended_cab_type ? `Recommended: ${transport.details.recommended_cab_type}` : null;
  return <div className="flex items-stretch gap-3 py-2"><div className="w-9 flex flex-col items-center shrink-0"><span className="w-px flex-1 bg-[#0C3B5E]/15" /><div className="w-7 h-7 rounded-full bg-[#0C3B5E] flex items-center justify-center my-1"><ModeIcon mode={transport.recommended_mode} className="text-[#22C55E]" /></div><span className="w-px flex-1 bg-[#0C3B5E]/15" /></div><div className="flex-1 rounded-xl bg-white border border-[#0C3B5E]/10 px-3.5 py-3 my-1"><div className="flex items-center justify-between gap-2 mb-1"><p className="text-[11px] text-[#0C3B5E]/50">{from} → {to}</p><span className="text-[9px] font-mono uppercase px-1.5 py-0.5 rounded-full bg-[#8B7FD6]/15 text-[#6B5FB6]">AI recommended</span></div><p className="text-sm font-semibold text-[#0C3B5E] capitalize mb-1">{transport.recommended_label || transport.recommended_mode?.replace('_',' ')}</p><div className="flex flex-wrap gap-x-3 gap-y-1 text-xs text-[#0C3B5E]/65 mb-1.5"><span>{transport.distance} km</span><span>{transport.duration} min</span><span>₹{transport.fare_per_person}/person{transport.travellers > 1 && ` · ₹${transport.total_fare} total`}</span></div>{detail && <p className="text-[11px] text-[#0C3B5E]/50 mb-1.5">{detail}</p>}{transport.recommendation_reason && <p className="text-xs text-[#0C3B5E]/70 leading-relaxed mb-2 italic">"{transport.recommendation_reason}"</p>}{transport.booking_url && <a href={transport.booking_url} target="_blank" rel="noreferrer" className="text-[11px] font-semibold text-[#2563EB]">Book via {transport.booking_provider} <ExternalLink size={10} className="inline" /></a>}{transport.alternative_options?.length > 0 && <button onClick={() => setExpanded(v=>!v)} className="ml-3 text-[11px] text-[#0C3B5E]/55">{transport.alternative_options.length} more option(s) <ChevronDown size={12} className={`inline ${expanded?'rotate-180':''}`} /></button>}{expanded && <div className="mt-2 pt-2 border-t border-[#0C3B5E]/8 space-y-2">{transport.alternative_options.map(opt => <div key={opt.mode} className="text-[11px] text-[#0C3B5E]/60">{opt.label} · ₹{opt.fare_per_person}/person · {opt.duration_minutes} min</div>)}</div>}</div></div>;
}

function WeatherIcon({ note, size = 12 }) { const lower=(note||'').toLowerCase(); if(lower.includes('rain')||lower.includes('drizzle')||lower.includes('storm')) return <CloudRain size={size}/>; if(lower.includes('cloud')||lower.includes('overcast')||lower.includes('fog')) return <Cloud size={size}/>; return <Sun size={size}/>; }

export default function ItineraryResults() {
  const { tripId } = useParams();
  const routerLocation = useLocation();
  const navigate = useNavigate();
  const [itinerary, setItinerary] = useState(routerLocation.state?.itinerary || null);
  const [hiddenGems, setHiddenGems] = useState(routerLocation.state?.hiddenGems || []);
  const [loading, setLoading] = useState(!routerLocation.state?.itinerary);
  const [regenerating, setRegenerating] = useState(false);
  const [regeneratingStop, setRegeneratingStop] = useState(null);
  const [error, setError] = useState('');
  const [stopError, setStopError] = useState('');
  const [downloading, setDownloading] = useState(false);
  const [downloadError, setDownloadError] = useState('');

  useEffect(() => { if(itinerary) return; api.getLatestItinerary(tripId).then(res=>setItinerary(res.itinerary)).catch(err=>setError(err.message)).finally(()=>setLoading(false)); }, [tripId]);
  const handleRegenerate = async () => { setRegenerating(true); setError(''); try { const res=await api.generateItinerary(tripId); setItinerary(res.itinerary); setHiddenGems(res.hiddenGems||[]); } catch(err){setError(err.message);} finally{setRegenerating(false);} };
  const handleDownloadPdf = async () => { setDownloading(true); setDownloadError(''); try { const {blob,filename}=await api.downloadItineraryPdf(tripId); const url=window.URL.createObjectURL(blob); const link=document.createElement('a'); link.href=url; link.download=filename; document.body.appendChild(link); link.click(); link.remove(); window.URL.revokeObjectURL(url); } catch(err){setDownloadError(err.message);} finally{setDownloading(false);} };
  const handleRegenerateStop = async stopOrder => { setRegeneratingStop(stopOrder); setStopError(''); try { const res=await api.regenerateStop(tripId,stopOrder); setItinerary(res.itinerary); } catch(err){setStopError(err.message);} finally{setRegeneratingStop(null);} };
  if(loading) return <div className="min-h-screen bg-[#EAF7EF] flex items-center justify-center"><Loader2 className="animate-spin text-[#2563EB]" size={32}/></div>;
  if(error&&!itinerary) return <div className="min-h-screen bg-[#EAF7EF] flex flex-col items-center justify-center px-6 text-center"><p className="text-[#0C3B5E]/70 mb-4">{error}</p><button onClick={()=>navigate(-1)} className="text-[#2563EB] font-semibold text-sm">Go back</button></div>;
  const stops=itinerary?.stops||[];
  const dayGroups=useMemo(()=>{const map=new Map(); stops.forEach(stop=>{const day=stop.day??1;if(!map.has(day))map.set(day,{day,date:stop.date||null,stops:[]});map.get(day).stops.push(stop);});return [...map.values()].sort((a,b)=>a.day-b.day);},[stops]);
  const budget=itinerary?.budget_summary||{}; const aiSummary=budget.ai_extras?.summary||budget.ai_extras?.final_ai_summary||null; const packingList=budget.ai_extras?.packing_list||[]; const localEvents=budget.ai_extras?.local_events||[]; const decisionExplanation=budget.ai_extras?.decision_explanation||[]; const confidenceScores=budget.ai_extras?.confidence_scores||null; const learnedPreferences=budget.ai_extras?.learned_preferences||null; const journey=budget.ai_extras?.journey||null; const routeSummary=journey?.route_summary||null; const accommodation=budget.ai_extras?.accommodation||null;
  const navigationUrl = null;
  const primaryLocation=stops[0]?{name:stops[0].name,lat:stops[0].latitude,lng:stops[0].longitude}:journey?.end?.location?{name:journey.end.location,lat:journey.end.latitude,lng:journey.end.longitude}:null;
  return <div className="min-h-screen bg-[#EAF7EF] px-4 sm:px-6 py-8 max-w-2xl mx-auto">
    <div className="flex items-center gap-2 mb-6"><div className="w-9 h-9 rounded-xl bg-[#0C3B5E] flex items-center justify-center rotate-[-8deg]"><Compass className="text-[#22C55E]" size={16}/></div><span className="font-bold text-lg text-[#0C3B5E]">GoVIBE</span></div>
    <h1 className="font-bold text-2xl text-[#0C3B5E] mb-1">Your optimized itinerary</h1><p className="text-sm text-[#0C3B5E]/55 mb-4">{routeSummary?.number_of_stops??stops.length} stops · {routeSummary?.total_distance_km??itinerary?.total_distance_km??0} km · ~{Math.round((routeSummary?.total_travel_minutes??itinerary?.total_duration_minutes??0)/60)}h travel</p>

    {accommodation && <div className="rounded-2xl bg-white border border-[#0C3B5E]/10 p-4 mb-6">
      <p className="flex items-center gap-1.5 text-xs font-mono uppercase tracking-wide text-[#0C3B5E]/45 mb-3"><Building2 size={13}/> Recommended Stay</p>
      <div className="flex items-start justify-between gap-3 mb-1.5"><p className="font-bold text-[15px] text-[#0C3B5E]">{accommodation.name}</p>{accommodation.rating!=null&&<span className="flex items-center gap-1 text-xs font-semibold bg-[#22C55E]/20 px-2 py-0.5 rounded-full"><Star size={11} className="fill-[#22C55E] text-[#22C55E]"/>{accommodation.rating}</span>}</div>
      {accommodation.address&&<p className="text-xs text-[#0C3B5E]/55 mb-2">{accommodation.address}</p>}
      <div className="flex flex-wrap items-center gap-2 mb-3"><span className="text-xs font-semibold text-[#0C3B5E] bg-[#EAF7EF] rounded-lg px-2.5 py-1">Current price · check live price for your dates</span>{accommodation.distance_km_from_center!=null&&<span className="text-xs text-[#0C3B5E]/60">{accommodation.distance_km_from_center} km from destination center</span>}</div>
      {accommodation.reason&&<p className="text-xs text-[#0C3B5E]/60 italic mb-3">{accommodation.reason}</p>}
      <div className="flex flex-wrap items-center gap-2">
        {accommodation.price_check_url&&<a href={accommodation.price_check_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 text-xs font-semibold text-white bg-[#0C3B5E] rounded-lg px-3 py-2">Check Current Price <ExternalLink size={11}/></a>}
        {accommodation.website_url&&<a href={accommodation.website_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#2563EB] border border-[#2563EB]/20 rounded-lg px-3 py-2">Hotel Website <ExternalLink size={11}/></a>}
        {accommodation.maps_url&&<a href={accommodation.maps_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#0C3B5E]/70 border border-[#0C3B5E]/10 rounded-lg px-3 py-2">Maps <MapPinned size={11}/></a>}
        {accommodation.phone&&<a href={`tel:${accommodation.phone}`} className="inline-flex items-center gap-1 text-xs font-semibold text-[#16A34A] px-2 py-2"><Phone size={12}/>{accommodation.phone}</a>}
      </div>
    </div>}

    {aiSummary&&<div className="rounded-2xl bg-[#0C3B5E] text-white p-4 mb-6 flex gap-3"><Sparkles size={18} className="text-[#22C55E] shrink-0"/><div><p className="text-xs font-mono uppercase tracking-wide text-white/50 mb-1">Why this plan fits you</p><p className="text-sm leading-relaxed text-white/90">{aiSummary}</p></div></div>}
    {decisionExplanation.length>0&&<div className="rounded-2xl bg-white border border-[#0C3B5E]/10 p-4 mb-6"><p className="text-xs font-mono uppercase tracking-wide text-[#0C3B5E]/45 mb-2"><ListChecks size={13} className="inline"/> How the AI decided</p><ul className="space-y-1.5">{decisionExplanation.map((line,i)=><li key={i} className="text-xs text-[#0C3B5E]/70">• {line}</li>)}</ul>{learnedPreferences&&<p className="mt-3 pt-3 border-t border-[#0C3B5E]/5 text-[11px] text-[#0C3B5E]/45">Personalized using patterns from your last {learnedPreferences.trips_analyzed} trips.</p>}</div>}
    {confidenceScores&&<div className="rounded-2xl bg-white border border-[#0C3B5E]/10 p-4 mb-6"><div className="flex justify-between mb-3"><p className="text-xs font-mono uppercase text-[#0C3B5E]/45">AI confidence</p><span className="text-sm font-bold">{confidenceScores.overall}%</span></div>{[['Interest match',confidenceScores.interest_match],['Budget accuracy',confidenceScores.budget_accuracy],['Route efficiency',confidenceScores.route_efficiency],['Weather suitability',confidenceScores.weather_suitability],['Transport optimization',confidenceScores.transport_optimization]].map(([label,value])=><div key={label} className="mb-2"><div className="flex justify-between text-[11px] text-[#0C3B5E]/60"><span>{label}</span><span>{value}%</span></div><div className="h-1.5 rounded-full bg-[#0C3B5E]/8"><div className="h-full rounded-full bg-[#16A34A]" style={{width:`${value}%`}}/></div></div>)}</div>}
    {stops[0]?.weather_note&&<div className="flex items-center gap-2 text-xs text-[#0C3B5E]/60 mb-6"><WeatherIcon note={stops[0].weather_note}/>{stops[0].weather_note}</div>}
    <div className="flex flex-wrap gap-2 mb-6"><button onClick={handleRegenerate} disabled={regenerating} className="flex items-center gap-1.5 text-xs font-semibold bg-white border border-[#0C3B5E]/15 rounded-xl px-3 py-2"><RefreshCw size={13} className={regenerating?'animate-spin':''}/>{regenerating?'Regenerating…':'Regenerate itinerary'}</button><button onClick={handleDownloadPdf} disabled={downloading} className="flex items-center gap-1.5 text-xs font-semibold bg-white border border-[#0C3B5E]/15 rounded-xl px-3 py-2"><Download size={13}/>{downloading?'Preparing…':'Download PDF'}</button></div>
    {error&&<p className="text-xs text-red-500 mb-4">{error}</p>}{downloadError&&<p className="text-xs text-red-500 mb-4">{downloadError}</p>}{stopError&&<p className="text-xs text-red-500 mb-4">{stopError}</p>}
    {dayGroups.map((group,groupIdx)=>{const isFirst=groupIdx===0,isLast=groupIdx===dayGroups.length-1;return <div key={group.day} className="mb-6"><p className="text-xs font-mono uppercase tracking-wide text-[#0C3B5E]/45 mb-2"><CalendarHeart size={13} className="inline"/> Day {group.day}{group.date?` · ${group.date}`:''}</p>{isFirst&&<JourneyEndpoint icon={Flag} label="Start" location={journey?.start?.location} time={journey?.start?.start_time_display} timeLabel="Departure"/>}{group.stops.map(stop=><div key={stop.order??stop.name}>{stop.transport?<TransportLegCard transport={stop.transport} from={stop.from_location_name} to={stop.name}/>:<TravelSegment from={stop.from_location_name} to={stop.name} distanceKm={stop.distance_km_from_prev} minutes={stop.travel_minutes_from_prev} mode={stop.transport_mode}/>}<div className="rounded-2xl bg-white border border-[#0C3B5E]/10 p-4 my-1"><div className="flex items-start justify-between gap-2 mb-1.5"><div><p className="font-bold text-[15px] text-[#0C3B5E]">{stop.order!=null?`${stop.order}. `:''}{stop.name}</p>{stop.category&&<span className="text-[10px] font-mono uppercase text-[#0C3B5E]/45 capitalize">{stop.category}</span>}</div>{stop.rating!=null&&<span className="flex items-center gap-1 text-xs font-semibold bg-[#22C55E]/20 px-2 py-0.5 rounded-full"><Star size={11} className="fill-[#22C55E] text-[#22C55E]"/>{stop.rating}</span>}</div><div className="flex flex-wrap gap-x-3 gap-y-1 text-xs text-[#0C3B5E]/70 mb-1.5">{stop.arrival_time&&<span><Clock size={11} className="inline"/> {stop.arrival_time}{stop.departure_time?` – ${stop.departure_time}`:''}</span>}{stop.visit_minutes!=null&&<span><TimerReset size={11} className="inline"/> {stop.visit_minutes} min</span>}{stop.entry_cost_inr!=null&&<span><IndianRupee size={11} className="inline"/> {stop.entry_cost_inr>0?`₹${stop.entry_cost_inr}`:'Free entry'}</span>}</div>{(stop.reasoning||stop.tips)&&<p className="text-xs text-[#0C3B5E]/60 italic mb-2">{stop.reasoning||stop.tips}</p>}{stop.meal_suggestion?.name&&<p className="text-xs text-[#0C3B5E]/70 mb-2"><UtensilsCrossed size={12} className="inline"/> {stop.meal_suggestion.name}{stop.meal_suggestion.avg_cost_inr!=null&&` · ~₹${stop.meal_suggestion.avg_cost_inr}`}</p>}<button onClick={()=>handleRegenerateStop(stop.order)} disabled={regeneratingStop===stop.order} className="text-[11px] font-medium text-[#0C3B5E]/55"><RefreshCw size={11} className={`inline ${regeneratingStop===stop.order?'animate-spin':''}`}/> {regeneratingStop===stop.order?'Swapping…':'Swap this stop'}</button></div></div>)}{isLast&&journey?.end?.location&&<><TravelSegment from={journey.end.from_location_name} to={journey.end.location} distanceKm={journey.end.distance_km_from_prev} minutes={journey.end.travel_minutes_from_prev} mode={journey.end.transport_mode}/><JourneyEndpoint icon={Flag} label="End" location={journey.end.location} time={journey.end.estimated_completion_time} timeLabel="Estimated arrival"/></>}</div>})}
    {hiddenGems.length>0&&<div className="rounded-2xl bg-white border border-[#0C3B5E]/10 p-4 mb-6"><p className="text-xs font-mono uppercase text-[#0C3B5E]/45 mb-3"><Gem size={13} className="inline"/> Hidden gems nearby</p>{hiddenGems.map(gem=><div key={gem.id} className="flex justify-between gap-2 mb-3"><div><p className="text-sm font-semibold">{gem.name}</p>{gem.reason&&<p className="text-xs text-[#0C3B5E]/55">{gem.reason}</p>}</div>{gem.rating!=null&&<span>{gem.rating}</span>}</div>)}</div>}
    {packingList.length>0&&<div className="rounded-2xl bg-white border border-[#0C3B5E]/10 p-4 mb-6"><p className="text-xs font-mono uppercase text-[#0C3B5E]/45 mb-3"><Luggage size={13} className="inline"/> Packing list</p><ul className="grid sm:grid-cols-2 gap-1.5">{packingList.map((item,i)=><li key={i} className="text-xs">• {item}</li>)}</ul></div>}
    {localEvents.length>0&&<div className="rounded-2xl bg-white border border-[#0C3B5E]/10 p-4 mb-6"><p className="text-xs font-mono uppercase text-[#0C3B5E]/45 mb-3"><CalendarHeart size={13} className="inline"/> Local events during your trip</p>{localEvents.map((ev,i)=><div key={i} className="mb-2"><p className="text-sm font-semibold">{ev.name} <span className="font-normal text-[#0C3B5E]/50">· {ev.date}</span></p>{ev.note&&<p className="text-xs text-[#0C3B5E]/55">{ev.note}</p>}</div>)}</div>}
    <div className="grid grid-cols-3 gap-2"><Link to={`/trip/${tripId}/budget`} state={{itinerary}} className="flex flex-col items-center gap-1.5 rounded-2xl bg-white border border-[#0C3B5E]/10 py-3 text-center"><Wallet size={18}/><span className="text-[11px] font-semibold">Budget Tracker</span></Link><Link to={`/trip/${tripId}/emergency-services`} state={{location:primaryLocation}} className="flex flex-col items-center gap-1.5 rounded-2xl bg-white border border-[#0C3B5E]/10 py-3 text-center"><ShieldPlus size={18}/><span className="text-[11px] font-semibold">Emergency Services</span></Link><Link to={`/trip/${tripId}/booking`} state={{itinerary}} className="flex flex-col items-center gap-1.5 rounded-2xl bg-white border border-[#0C3B5E]/10 py-3 text-center"><Ticket size={18}/><span className="text-[11px] font-semibold">Bookings</span></Link></div>
  </div>;
}
